# Site
name: "GGG"
title: "USC - Geometry and Graphics Group"
description: "The group website for USC's Geometry and Graphics Group. Come here for our latest publications, and more!"
logo: 'assets/images/research-group-logo.png'
favicon: 'assets/images/favicon.png'
include: ["_pages"]

# Authors
authors:
  oded:
    name: Oded Stein
    display_name: Oded Stein
    email: ostein@usc.edu
    web: https://odedstein.com
    description: "Professor of USC GGG"

# Plugins
# plugins:
#   - jekyll-paginate
#   - jekyll-sitemap
#   - jekyll-feed
#   - jekyll-seo-tag
#   - jekyll-archives
    
# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [LICENSE.txt]
